-- Verificación rápida de schema (Oracle). Ejecutar como controlgastos.
-- Esperado: sin "MISSING" en la salida.

SET PAGESIZE 100 FEEDBACK OFF VERIFY OFF HEADING ON

PROMPT === Tablas ===
SELECT t.nombre AS tabla,
       CASE WHEN u.table_name IS NULL THEN 'MISSING' ELSE 'ok' END AS estado
FROM (
  SELECT 'CG_USUARIO' nombre FROM dual UNION ALL
  SELECT 'CG_CUENTA' FROM dual UNION ALL
  SELECT 'CG_INGRESO' FROM dual UNION ALL
  SELECT 'CG_GASTO' FROM dual UNION ALL
  SELECT 'CG_GASTO_MENSUAL' FROM dual UNION ALL
  SELECT 'CG_MOVIMIENTO' FROM dual UNION ALL
  SELECT 'CG_SALDO' FROM dual UNION ALL
  SELECT 'CG_DENOMINACION' FROM dual UNION ALL
  SELECT 'CG_HISTORIAL_ANUAL' FROM dual UNION ALL
  SELECT 'CG_PERSONA_COMPARTIDA' FROM dual UNION ALL
  SELECT 'CG_SERVICIO_FIJO_COMPARTIDO' FROM dual UNION ALL
  SELECT 'CG_GASTO_COMPARTIDO' FROM dual UNION ALL
  SELECT 'CG_PARTE_GASTO_COMPARTIDO' FROM dual UNION ALL
  SELECT 'CG_MOV_PERSONA_COMPARTIDA' FROM dual
) t
LEFT JOIN user_tables u ON u.table_name = t.nombre
ORDER BY 1;

PROMPT === CG_GASTO MSI / disposición ===
SELECT c.nombre AS columna,
       CASE WHEN u.column_name IS NULL THEN 'MISSING' ELSE 'ok' END AS estado
FROM (
  SELECT 'MESES' nombre FROM dual UNION ALL
  SELECT 'CUOTA_MENSUAL' FROM dual UNION ALL
  SELECT 'FORMA_PAGO' FROM dual
) c
LEFT JOIN user_tab_columns u
  ON u.table_name = 'CG_GASTO' AND u.column_name = c.nombre
ORDER BY 1;

PROMPT === CG_GASTO_MENSUAL MSI ===
SELECT c.nombre AS columna,
       CASE WHEN u.column_name IS NULL THEN 'MISSING' ELSE 'ok' END AS estado
FROM (
  SELECT 'MESES_TOTALES' nombre FROM dual UNION ALL
  SELECT 'MESES_RESTANTES' FROM dual UNION ALL
  SELECT 'MONTO_TOTAL' FROM dual UNION ALL
  SELECT 'GASTO_ORIGEN_ID' FROM dual UNION ALL
  SELECT 'SERVICIO_FIJO_COMPARTIDO_ID' FROM dual UNION ALL
  SELECT 'DIA_PAGO' FROM dual
) c
LEFT JOIN user_tab_columns u
  ON u.table_name = 'CG_GASTO_MENSUAL' AND u.column_name = c.nombre
ORDER BY 1;

EXIT
