spring.application.name=control-gastos
server.port=8081

spring.datasource.url=jdbc:h2:file:./data/control-gastos;MODE=Oracle;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

spring.jackson.serialization.write-dates-as-timestamps=false
